name: www.professionalize.com
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: professionalize/professionalize
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.135.0'
          extended: true
    - name: Determine Base URL
      id: base-url
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "::set-output name=url::https://www.professionalize.com"
        else
          echo "::set-output name=url::https://qa.professionalize.com"
        fi
    - name: Build Site
      run: hugo --config "configs/www.professionalize.com.toml","configs/common.professionalize.com.toml" -b "${{ steps.base-url.outputs.url }}" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Sync to S3
      run: |
        aws s3 sync . s3://www-professionalize-com
      working-directory: public
      env:
        AWS_ENDPOINT_URL: https://s3.dynabic.com
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
